name: Build & Test SolarGainESP32

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          ~/.cache/pip
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        
    - name: Build firmware
      run: |
        pio run -e esp32dev
        
    - name: Run unit tests
      run: |
        pio test -e esp32dev --without-uploading
        
    - name: Generate firmware info
      run: |
        echo "## Firmware Build Info" > firmware_info.txt
        echo "Build Date: $(date)" >> firmware_info.txt
        echo "Git Commit: ${{ github.sha }}" >> firmware_info.txt
        echo "Branch: ${{ github.ref_name }}" >> firmware_info.txt
        pio run -e esp32dev --target size | grep -A 20 "Memory Usage" >> firmware_info.txt || true
        
    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ github.sha }}
        path: |
          .pio/build/esp32dev/firmware.bin
          .pio/build/esp32dev/firmware.elf
          firmware_info.txt
        retention-days: 30
        
    - name: Upload SPIFFS image
      uses: actions/upload-artifact@v4
      with:
        name: spiffs-${{ github.sha }}
        path: |
          .pio/build/esp32dev/spiffs.bin
          data/config.json
        retention-days: 30

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        
    - name: Run static analysis
      run: |
        pio check -e esp32dev --skip-packages
        
  release:
    needs: [build, code-quality]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Download firmware artifact
      uses: actions/download-artifact@v4
      with:
        name: firmware-${{ github.sha }}
        
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          firmware.bin
          firmware.elf
          firmware_info.txt
        body: |
          ## SolarGainESP32 Firmware Release
          
          ### Installation Instructions
          1. Download `firmware.bin`
          2. Use ESP32 Flash Tool or PlatformIO to upload
          3. Upload SPIFFS data with your `config.json`
          
          ### What's New
          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)
        draft: false
        prerelease: false
